version: '2'
services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    ports:
    - 8888:8080
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./conf.d:/etc/nginx/conf.d
    - ./sites:/sites
